"""add pending_reviews table

Revision ID: e87401803cb0
Revises: 3cd8ff31948c
Create Date: 2026-08-31 20:16:35.405039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e87401803cb0'
down_revision: Union[str, None] = '3cd8ff31948c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('parsed_config_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('raw_line', sa.Text(), nullable=False),
    sa.Column('suggested_category', sa.String(), nullable=True),
    sa.Column('suggested_field', sa.String(), nullable=True),
    sa.Column('suggested_value', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['parsed_config_id'], ['parsed_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_reviews')
    # ### end Alembic commands ###
